name: Java CI

on:
  push:
    branches:
      - master
      - $default-branch
      - $protected-branches
  pull_request:
    branches:
      - master
      - $default-branch
  workflow_dispatch:

permissions:
  contents: write
  checks: write

jobs:
  call-workflow:
    strategy:
      matrix:
        josm-revision: ["", "r19017"]
    uses: JOSM/JOSMPluginAction/.github/workflows/ant.yml@v2
    with:
      java-version: 17
      josm-revision: ${{ matrix.josm-revision }}
      perform-revision-tagging: ${{ matrix.josm-revision == 'r19017' && github.repository == 'tsmock/sidewalks' && github.ref_type == 'branch' && github.ref_name == 'master' && github.event_name != 'schedule' && github.event_name != 'pull_request' }}
    secrets: inherit

